# Generated by Django 6.0.4 on 2026-04-21 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('distance_to_donors_avg', models.FloatField(blank=True, null=True)),
                ('shortest_distance', models.FloatField(blank=True, null=True)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('total_donors_notified', models.PositiveIntegerField(default=0)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('emergency_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='hospitals.emergencyrequest')),
            ],
        ),
        migrations.CreateModel(
            name='DonorResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.UUIDField()),
                ('response_time_seconds', models.FloatField()),
                ('distance_meters', models.FloatField()),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='analytics.requestlog')),
            ],
        ),
    ]
